networks:
  socket_proxy:
    name: socket_proxy

services:
  dozzle-agent:
    image: amir20/dozzle:v8.14.7
    command: agent
    restart: unless-stopped
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOCKER_HOST: tcp://socketproxy:2375
    # This is used in machines exposed to the internet
    # and not managed by proxmox. This means that technically
    # this port is open to the world. But the router
    # properly handles firewall in this case. Just be careful
    # if you take this setup without caring with the router firewall
    ports:
      - 7007:7007
    networks:
      - socket_proxy
    depends_on:
      - socketproxy
  socketproxy:
    image: tecnativa/docker-socket-proxy:0.3.0
    privileged: true
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      ALLOW_START: 1
      ALLOW_RESTARTS: 1
      ALLOW_STOP: 1
      INFO: 1
      CONFIGS: 1
      IMAGES: 1
      NETWORKS: 1
      SYSTEM: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy
