---
homelab:
  hosts:
    raspberrypi:
      ansible_host: 192.168.20.3
      ansible_user: lorenzo
      ansible_architecture: arm
      ansible_distribution: debian
    radioactive:
      ansible_host: 192.168.20.5
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    obsidian:
      ansible_host: 192.168.40.18
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    confidant:
      ansible_host: 192.168.40.19
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    l-tracker:
      ansible_host: 192.168.40.27
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    forgejo:
      ansible_host: 192.168.40.16
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    lofinance:
      ansible_host: 192.168.40.24
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    hoarder:
      ansible_host: 192.168.40.28
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    pihole:
      ansible_host: 192.168.40.7
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    nginx-proxy-manager:
      ansible_host: 192.168.40.14
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    unifi-controller:
      ansible_host: 192.168.40.23
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    dozzle:
      ansible_host: 192.168.40.25
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    uptime-kuma:
      ansible_host: 192.168.40.33
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian
    # hares:
    #   ansible_host: 192.168.40.36
    #   ansible_user: lorenzo
    #   ansible_architecture: amd64
    #   ansible_distribution: debian
    owntracks:
      ansible_host: 192.168.40.37
      ansible_user: lorenzo
      ansible_architecture: amd64
      ansible_distribution: debian



